#!/usr/bin/env python3
"""
Replay All Video Sync & Segmentation Cutter (FFmpeg)
-----------------------------------------------------
Cuts one or two multi-camera study video recordings based on CSV timestamps generated by ReplayAllManager.

Workflow:
  1. Audio Synchronization: Finds the exact timestamp inside each video where the initial 
     clapperboard emergency sound (EventBus.publish('fault') at self.start_time_epoch) occurs.
     Can be specified manually (--sync-time-1, --sync-time-2) or detected automatically (--auto-sync).
  2. CSV Parsing: Reads all 'Start' and 'End' ElapsedSeconds for each gesture ID (e.g. P1_R1_A) from the CSV.
  3. Video Segmentation: Cuts exact gesture video clips for Camera 1 and Camera 2 starting at 
     `sync_time + E_start` and ending at `sync_time + E_end`, naming each file `<ID>.mp4`.
  4. Test Mode (--max-clips / -n): Limits how many clips are cut so you can test alignment first.
"""

import os
import sys
import csv
import time
import argparse
import subprocess
import tempfile
from pathlib import Path

# Enable VT100 ANSI colors on Windows terminal
if os.name == 'nt':
    os.system("")

COLOR_RESET = "\033[0m"
COLOR_CYAN = "\033[96m"
COLOR_GREEN = "\033[92m"
COLOR_YELLOW = "\033[93m"
COLOR_RED = "\033[91m"


def print_info(msg):
    print(f"{COLOR_CYAN}[INFO]{COLOR_RESET} {msg}")


def print_success(msg):
    print(f"{COLOR_GREEN}[SUCCESS]{COLOR_RESET} {msg}")


def print_warning(msg):
    print(f"{COLOR_YELLOW}[WARNING]{COLOR_RESET} {msg}")


def print_error(msg):
    print(f"{COLOR_RED}[ERROR]{COLOR_RESET} {msg}")


def check_ffmpeg():
    """Verifies that ffmpeg is installed and accessible on PATH."""
    try:
        subprocess.run(["ffmpeg", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print_error("FFmpeg not found on PATH! Please install FFmpeg and make sure it is in your environment variables.")
        return False


def detect_sync_audio_offset(video_path, ref_sound_path, threshold_db=-22.0):
    """
    Automatically detects the exact start offset (in seconds) where the initial clapperboard sound occurs.
    Uses cross-correlation if scipy/numpy are available along with ref_sound_path, otherwise uses FFmpeg silencedetect.
    Fast-mode enabled (`-vn -t 180`) to finish within < 0.5 seconds without decoding video frames.
    """
    print_info(f"Analyzing first 3 minutes of audio track in '{video_path}' to detect sync cue (fast-mode enabled)...")
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    ref_resolved = resolve_file_path(ref_sound_path, script_dir)
    ref_exists = ref_resolved and os.path.exists(ref_resolved)
    
    # Check if scipy/numpy are available for high-precision waveform cross-correlation
    has_scipy = False
    try:
        import numpy as np
        import scipy.io.wavfile as wavfile
        import scipy.signal as signal
        has_scipy = True
    except ImportError:
        pass

    if has_scipy and ref_exists:
        print_info(f"Using high-precision FFT cross-correlation with reference audio '{ref_resolved}'...")
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                vid_wav = os.path.join(tmpdir, "vid_audio.wav")
                ref_wav = os.path.join(tmpdir, "ref_audio.wav")
                
                # Extract up to first 180 seconds of video audio at 16kHz mono without decoding video frames (`-vn -t 180`)
                cmd_vid = ["ffmpeg", "-y", "-t", "180", "-i", video_path, "-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1", vid_wav]
                subprocess.run(cmd_vid, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
                
                # Convert ref sound to 16kHz mono WAV
                cmd_ref = ["ffmpeg", "-y", "-i", ref_resolved, "-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1", ref_wav]
                subprocess.run(cmd_ref, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
                
                # Load audio arrays
                sr_v, data_v = wavfile.read(vid_wav)
                sr_r, data_r = wavfile.read(ref_wav)
                
                # Normalize float arrays
                data_v = data_v.astype(np.float32)
                data_r = data_r.astype(np.float32)
                data_v = (data_v - np.mean(data_v)) / (np.std(data_v) + 1e-9)
                data_r = (data_r - np.mean(data_r)) / (np.std(data_r) + 1e-9)
                
                # Limit cross-correlation search window to first 180 seconds
                max_samples = min(len(data_v), int(180 * sr_v))
                data_v_slice = data_v[:max_samples]
                
                # Explicitly use FFT for O(N log N) speed (< 0.1s)
                corr = signal.correlate(data_v_slice, data_r, mode="valid", method="fft")
                peak_sample = np.argmax(corr)
                sync_time = float(peak_sample) / sr_v
                print_success(f"Detected sync audio cue via FFT cross-correlation at: {sync_time:.3f}s")
                return sync_time
        except Exception as e:
            print_warning(f"Cross-correlation failed ({e}). Falling back to fast threshold detection (`silencedetect`).")

    # Fallback to FFmpeg silencedetect / energy threshold (with `-vn -t 180` to prevent CPU video decoding)
    print_info("Using fast FFmpeg audio threshold detection (`silencedetect`) to locate first sharp audio cue...")
    cmd = [
        "ffmpeg", "-t", "180", "-i", video_path,
        "-vn",
        "-af", f"silencedetect=noise={threshold_db}dB:d=0.08",
        "-f", "null", "-"
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    
    # Look for the first silence_end timestamp in ffmpeg stderr output
    for line in res.stderr.splitlines():
        if "silence_end:" in line:
            parts = line.split("silence_end:")
            if len(parts) > 1:
                val_str = parts[1].split()[0]
                try:
                    sync_time = float(val_str)
                    print_success(f"Detected first loud sound event (silence end) at: {sync_time:.3f}s")
                    return sync_time
                except ValueError:
                    continue
                    
    print_warning("Could not automatically pinpoint sync audio cue. Defaulting to 0.0s offset.")
    return 0.0


def parse_csv_timestamps(csv_path):
    """
    Parses start and end timestamps grouped by gesture ID.
    Supports:
      - Replay All CSVs: columns ['ID', 'Event', 'ElapsedSeconds']
      - Session Study Logs: columns ['id'/'name', 'starttime', 'endtime']
    """
    if not os.path.exists(csv_path):
        print_error(f"CSV file '{csv_path}' not found.")
        return []

    segments = {}
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Check if this is a ReplayAll log ('ID', 'Event', 'ElapsedSeconds')
            gid = (row.get("ID") or row.get("id") or row.get("gesture_file") or "").strip()
            event = (row.get("Event") or row.get("event") or "").strip()
            elapsed_str = (row.get("ElapsedSeconds") or row.get("elapsed") or row.get("Timestamp") or "").strip()

            if gid and event in ("Start", "End") and elapsed_str:
                try:
                    elapsed = float(elapsed_str)
                    if gid not in segments:
                        segments[gid] = {"id": gid, "start": None, "end": None}
                    if event == "Start":
                        segments[gid]["start"] = elapsed
                    elif event == "End":
                        segments[gid]["end"] = elapsed
                except ValueError:
                    continue
            else:
                # Check if it's a standard session study_log-*.csv ('starttime', 'endtime')
                start_str = (row.get("starttime") or row.get("Starttime") or "").strip()
                end_str = (row.get("endtime") or row.get("Endtime") or "").strip()
                if gid and start_str and end_str:
                    try:
                        t_s = float(start_str)
                        t_e = float(end_str)
                        # If epochs > 1 billion, compute relative duration
                        segments[gid] = {"id": gid, "start": 0.0, "end": round(t_e - t_s, 3)}
                    except ValueError:
                        continue

    # Filter out incomplete segments
    valid_clips = []
    for gid, data in segments.items():
        if data["start"] is not None and data["end"] is not None and data["end"] > data["start"]:
            valid_clips.append(data)
            
    # Sort chronologically by start time
    valid_clips.sort(key=lambda x: x["start"])
    return valid_clips


def cut_video_segment(video_path, start_t, duration_s, output_path, reencode=False, rotate_deg=None):
    """
    Executes FFmpeg cut for a single video segment.
    Handles iPhone .mov rotation/orientation tags properly so videos never flip 180 degrees.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    
    vf_filters = []
    if rotate_deg == "180":
        vf_filters.append("vflip,hflip")
    elif rotate_deg == "90":
        vf_filters.append("transpose=1")
    elif rotate_deg == "270":
        vf_filters.append("transpose=2")
    elif rotate_deg in ("hflip", "vflip"):
        vf_filters.append(rotate_deg)

    if reencode or vf_filters:
        # High precision re-encode (exact sample frame cutting + orientation reset + universal yuv420p 8-bit color profile)
        # Note: FFmpeg automatically decodes iPhone .mov upright (`autorotate`). 
        # Setting `-metadata:s:v:0 rotate=0` ensures players don't rotate the already-upright output another 180 degrees!
        cmd = [
            "ffmpeg", "-y",
            "-ss", f"{start_t:.3f}",
            "-i", video_path,
            "-t", f"{duration_s:.3f}"
        ]
        if vf_filters:
            cmd.extend(["-vf", ",".join(vf_filters)])
        cmd.extend([
            "-c:v", "libx264", "-preset", "fast", "-crf", "18",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-metadata:s:v:0", "rotate=0",
            "-movflags", "+faststart",
            output_path
        ])
    else:
        # Fast stream copy (non-lossy, copies original container display matrix/orientation tags accurately)
        # Includes `-tag:v hvc1` so Apple/Windows players recognize HEVC streams copied into .mp4 containers
        cmd = [
            "ffmpeg", "-y",
            "-ss", f"{start_t:.3f}",
            "-i", video_path,
            "-t", f"{duration_s:.3f}",
            "-c", "copy", "-avoid_negative_ts", "1",
            "-tag:v", "hvc1",
            "-map_metadata", "0",
            "-movflags", "+faststart",
            output_path
        ]
        
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return res.returncode == 0


def cut_side_by_side_segment(video1_path, v1_start, video2_path, v2_start, duration_s, output_path, scale_height=0, rotate_v1=None, rotate_v2=None):
    """
    Executes FFmpeg side-by-side horizontal stack ([0:v][1:v]hstack) with audio strictly from Video 1.
    Explicitly clears residual iPhone QuickTime `rotate` metadata on output so it won't flip 180 degrees.
    Enforces `-pix_fmt yuv420p` to ensure universal playback across QuickTime and Windows media players.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    
    # Build per-stream rotation filters if needed (e.g. if iPhone was mounted upside down on tripod)
    v0_filter = "vflip,hflip" if rotate_v1 == "180" else ("transpose=1" if rotate_v1 == "90" else ("transpose=2" if rotate_v1 == "270" else ("null" if not rotate_v1 else rotate_v1)))
    v1_filter = "vflip,hflip" if rotate_v2 == "180" else ("transpose=1" if rotate_v2 == "90" else ("transpose=2" if rotate_v2 == "270" else ("null" if not rotate_v2 else rotate_v2)))
    
    if scale_height > 0:
        filter_str = f"[0:v]{v0_filter},scale=-1:{scale_height}[v0];[1:v]{v1_filter},scale=-1:{scale_height}[v1];[v0][v1]hstack=inputs=2[v]"
    else:
        if v0_filter != "null" or v1_filter != "null":
            filter_str = f"[0:v]{v0_filter}[v0];[1:v]{v1_filter}[v1];[v0][v1]hstack=inputs=2[v]"
        else:
            filter_str = "[0:v][1:v]hstack=inputs=2[v]"
        
    cmd = [
        "ffmpeg", "-y",
        "-ss", f"{v1_start:.3f}", "-i", video1_path,
        "-ss", f"{v2_start:.3f}", "-i", video2_path,
        "-t", f"{duration_s:.3f}",
        "-filter_complex", filter_str,
        "-map", "[v]",
        "-map", "0:a?",
        "-c:v", "libx264", "-preset", "fast", "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k",
        "-metadata:s:v:0", "rotate=0",
        "-movflags", "+faststart",
        output_path
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if res.returncode != 0:
        print_error(f"FFmpeg side-by-side cut error: {res.stderr[:350]}")
    return res.returncode == 0


import glob

def resolve_file_path(path_str, script_dir):
    if not path_str:
        return None
    if os.path.exists(path_str):
        return path_str
    p_in_script = os.path.join(script_dir, path_str)
    if os.path.exists(p_in_script):
        return p_in_script
    p_in_root = os.path.join(script_dir, "..", path_str)
    if os.path.exists(p_in_root):
        return p_in_root
    return path_str


def autodetect_csv_log(script_dir):
    search_dirs = [
        script_dir,
        os.getcwd(),
        os.path.join(script_dir, "..", "study_results"),
        os.path.join(script_dir, "..")
    ]
    found_csvs = []
    for d in search_dirs:
        if os.path.exists(d):
            found_csvs.extend(glob.glob(os.path.join(d, "replay_all_log_*.csv")))
            found_csvs.extend(glob.glob(os.path.join(d, "study_log-*.csv")))
            found_csvs.extend(glob.glob(os.path.join(d, "*.csv")))
    
    # Unique and filter out non-log csvs
    unique_csvs = list(set([os.path.abspath(p) for p in found_csvs if os.path.isfile(p)]))
    if not unique_csvs:
        return None
    # Sort by modification time descending (newest log first)
    unique_csvs.sort(key=lambda p: os.path.getmtime(p), reverse=True)
    return unique_csvs[0]


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    parser = argparse.ArgumentParser(description="Extract and cut synced gesture clips from study videos using Replay All CSV.")
    parser.add_argument("--video1", "-v1", default="All1.mov", help="Path to Video 1 / Front View (defaults to autodetecting 'All1.mov' in current or script folder)")
    parser.add_argument("--video2", "-v2", default=None, help="Path to Video 2 / Side View (if omitted, autodetects 'All2.mov' if present in the same folder)")
    parser.add_argument("--csv", "-c", default=None, help="Path to the Replay All CSV log file (if omitted, autodetects the newest replay/study log CSV in the same folder)")
    parser.add_argument("--out-dir", "-o", default="cut_segments", help="Output directory where cut video segments will be saved")
    parser.add_argument("--max-clips", "-n", type=int, default=0, help="Maximum number of video segments to cut (test argument, e.g. -n 3)")
    
    # Side-by-Side compositing options
    parser.add_argument("--side-by-side", "--sbs", "-sbs", action="store_true", help="Combine Video 1 and Video 2 side-by-side horizontally into a single video file using audio from Video 1")
    parser.add_argument("--scale-height", type=int, default=0, help="Optional height in pixels (e.g. 720 or 1080) to scale both videos before side-by-side stacking (prevents height mismatch errors)")
    parser.add_argument("--keep-individual", action="store_true", help="When --side-by-side is active, also save individual cam1/ and cam2/ cuts alongside the side-by-side cuts")
    
    # iPhone / Orientation adjustment options
    parser.add_argument("--rotate-v1", choices=["90", "180", "270", "hflip", "vflip"], default=None, help="Explicitly rotate or flip Video 1 (e.g. 180 if iPhone recorded upside down)")
    parser.add_argument("--rotate-v2", choices=["90", "180", "270", "hflip", "vflip"], default=None, help="Explicitly rotate or flip Video 2 (e.g. 180 if iPhone recorded upside down)")
    
    # Sync options
    parser.add_argument("--sync-time-1", type=float, default=None, help="Manual start offset in seconds for Video 1 (where clapperboard beep occurs)")
    parser.add_argument("--sync-time-2", type=float, default=None, help="Manual start offset in seconds for Video 2 (where clapperboard beep occurs)")
    parser.add_argument("--auto-sync", action="store_true", help="Automatically detect audio sync cue inside video tracks")
    parser.add_argument("--ref-sound", default="sounds/3rdParty_Failure_Haptic.mp3", help="Reference sound file for cross-correlation auto-sync")
    
    # Padding and quality options
    parser.add_argument("--padding-start", type=float, default=0.0, help="Padding seconds added before each segment start (default: 0.0)")
    parser.add_argument("--padding-end", type=float, default=0.5, help="Padding seconds added after each segment end (default: 0.5)")
    parser.add_argument("--reencode", action="store_true", help="Re-encode video (`-c:v libx264`) for exact frame-accurate cuts instead of stream copy")
    
    args = parser.parse_args()

    if not check_ffmpeg():
        sys.exit(1)

    # Autodetect and resolve files if not passed explicitly
    v1_resolved = resolve_file_path(args.video1, script_dir)
    if not v1_resolved or not os.path.exists(v1_resolved):
        print_error(f"Video 1 file not found: '{args.video1}'. Please place 'All1.mov' in the script folder or pass `--video1 path/to/video.mov`.")
        sys.exit(1)
    args.video1 = v1_resolved

    # If video2 not specified, check if 'All2.mov' exists next to script or in current directory
    if args.video2 is None:
        v2_candidate = resolve_file_path("All2.mov", script_dir)
        if v2_candidate and os.path.exists(v2_candidate):
            args.video2 = v2_candidate
            print_info(f"Autodetected Video 2 (Side View): '{args.video2}'")
    else:
        v2_resolved = resolve_file_path(args.video2, script_dir)
        if not v2_resolved or not os.path.exists(v2_resolved):
            print_error(f"Video 2 file not found: '{args.video2}'.")
            sys.exit(1)
        args.video2 = v2_resolved

    # Resolve CSV or autodetect if not passed
    if args.csv is None:
        csv_resolved = autodetect_csv_log(script_dir)
        if not csv_resolved:
            print_error("No Replay All / study log CSV found in the current folder, script folder, or study_results/. Please specify `--csv path/to/log.csv`.")
            sys.exit(1)
        args.csv = csv_resolved
        print_info(f"Autodetected Replay All CSV Log: '{args.csv}'")
    else:
        csv_resolved = resolve_file_path(args.csv, script_dir)
        if not csv_resolved or not os.path.exists(csv_resolved):
            print_error(f"CSV log file not found: '{args.csv}'.")
            sys.exit(1)
        args.csv = csv_resolved

    if args.side_by_side and not args.video2:
        print_error("Cannot use --side-by-side (--sbs) without both Video 1 ('All1.mov') and Video 2 ('All2.mov') being present!")
        sys.exit(1)

    # 1. Determine Sync Offsets
    sync_1 = args.sync_time_1
    sync_2 = args.sync_time_2

    if args.auto_sync:
        if sync_1 is None:
            print_info("--- Running Auto-Sync Detection on Video 1 ---")
            sync_1 = detect_sync_audio_offset(args.video1, args.ref_sound)
        if args.video2 and sync_2 is None:
            print_info("--- Running Auto-Sync Detection on Video 2 ---")
            sync_2 = detect_sync_audio_offset(args.video2, args.ref_sound)

    sync_1 = sync_1 or 0.0
    sync_2 = sync_2 or 0.0

    print("\n=================== VIDEO SYNC ALIGNMENT ===================")
    print(f"  Video 1 Track: {args.video1} (@ +{sync_1:.3f}s)")
    if args.video2:
        print(f"  Video 2 Track: {args.video2} (@ +{sync_2:.3f}s)")
    if args.side_by_side:
        print(f"  Output Mode  : SIDE-BY-SIDE COMPOSITE (`hstack` with Video 1 audio)")
    else:
        print(f"  Output Mode  : INDIVIDUAL CAMERA FILES")
    print("============================================================\n")

    # 2. Parse CSV Segments
    clips = parse_csv_timestamps(args.csv)
    if not clips:
        print_error("No valid 'Start' and 'End' timestamp segments found in CSV.")
        sys.exit(1)

    total_available = len(clips)
    if args.max_clips > 0:
        clips = clips[:args.max_clips]
        print_info(f"Test limit (--max-clips / -n) active: Cutting first {len(clips)} of {total_available} segments.")
    else:
        print_info(f"Found {total_available} total gesture segments in CSV to cut.")

    # 3. Process Cut Loop
    if not os.path.isabs(args.out_dir):
        args.out_dir = os.path.join(script_dir, args.out_dir)
        
    os.makedirs(args.out_dir, exist_ok=True)
    sbs_dir = os.path.join(args.out_dir, "side_by_side") if args.side_by_side else None
    cam1_dir = os.path.join(args.out_dir, "cam1") if not args.side_by_side or args.keep_individual else None
    cam2_dir = os.path.join(args.out_dir, "cam2") if (not args.side_by_side or args.keep_individual) and args.video2 else None

    if sbs_dir: os.makedirs(sbs_dir, exist_ok=True)
    if cam1_dir: os.makedirs(cam1_dir, exist_ok=True)
    if cam2_dir: os.makedirs(cam2_dir, exist_ok=True)

    success_count = 0
    for idx, clip in enumerate(clips, 1):
        gid = clip["id"]
        # Apply padding and ensure start >= 0
        start_elapsed = max(0.0, clip["start"] - args.padding_start)
        end_elapsed = clip["end"] + args.padding_end
        duration = max(0.1, end_elapsed - start_elapsed)

        v1_start = sync_1 + start_elapsed
        v2_start = (sync_2 + start_elapsed) if args.video2 else 0.0

        print(f"\n[{idx}/{len(clips)}] Processing gesture '{gid}' (Elapsed: {start_elapsed:.2f}s -> {end_elapsed:.2f}s, Dur: {duration:.2f}s)...")
        
        ok = True
        # Side-by-Side compositing
        if args.side_by_side and sbs_dir and args.video2:
            sbs_out = os.path.join(sbs_dir, f"{gid}.mp4")
            print(f"  -> Side-by-Side Composite Cut: {sbs_out}")
            ok = cut_side_by_side_segment(args.video1, v1_start, args.video2, v2_start, duration, sbs_out, scale_height=args.scale_height, rotate_v1=args.rotate_v1, rotate_v2=args.rotate_v2)

        # Individual camera cuts
        if cam1_dir:
            v1_out = os.path.join(cam1_dir, f"{gid}.mp4")
            print(f"  -> Cam 1 Cut (@ {v1_start:.2f}s): {v1_out}")
            ok1 = cut_video_segment(args.video1, v1_start, duration, v1_out, reencode=args.reencode, rotate_deg=args.rotate_v1)
            ok = ok and ok1
            
        if cam2_dir and args.video2:
            v2_out = os.path.join(cam2_dir, f"{gid}.mp4")
            print(f"  -> Cam 2 Cut (@ {v2_start:.2f}s): {v2_out}")
            ok2 = cut_video_segment(args.video2, v2_start, duration, v2_out, reencode=args.reencode, rotate_deg=args.rotate_v2)
            ok = ok and ok2

        if ok:
            print_success(f"Successfully processed segment '{gid}'.")
            success_count += 1
        else:
            print_error(f"Failed to complete one or more cuts for segment '{gid}'.")

    print("\n================== CUTTING SEQUENCE COMPLETE ==================")
    print(f"  Successfully extracted {success_count} / {len(clips)} gesture clips to: '{args.out_dir}'")
    print("===============================================================\n")


if __name__ == "__main__":
    main()
